// Generated by CoffeeScript 1.10.0
(function() {
  var Jumbotron, React, ReactDOM, a, div, h1, p, ref;

  React = require('react');

  ReactDOM = require('react-dom');

  console.dir(React);

  console.dir(ReactDOM);

  console.dir(React);

  ref = React.DOM, div = ref.div, h1 = ref.h1, p = ref.p, a = ref.a;

  Jumbotron = React.createClass({
    render: function() {
      return div({
        className: "jumbotron"
      }, div({
        className: "container"
      }, h1({}, "Hello World"), p({}, a({
        className: "btn btn-primary btn-lg",
        href: "#",
        role: "button",
        "Learn more »": "Learn more »"
      }))));
    }
  });

}).call(this);
