// Generated by CoffeeScript 1.7.1
(function() {
  var Main, RaisedButton, React, ReactDOM, a, div, h1, injectTapEventPlugin, p, _ref;

  React = require('react');

  ReactDOM = require('react-dom');

  injectTapEventPlugin = require('react-tap-event-plugin');

  RaisedButton = require('material-ui/lib/raised-button');

  console.dir(React);

  console.dir(ReactDOM);

  console.dir(RaisedButton);

  _ref = React.DOM, div = _ref.div, h1 = _ref.h1, p = _ref.p, a = _ref.a;

  console.dir(div);

  Main = React.createClass({
    render: function() {
      return div({
        className: "jumbotron"
      }, h1({}, "Hello World", p({}, a({
        className: "btn btn-primary btn-lg",
        href: "#",
        role: "button"
      }, "Learn more »"))), React.createElement(RaisedButton, {
        label: "Super Secret Password"
      }));
    }
  });

  injectTapEventPlugin();

  ReactDOM.render(React.createElement(Main), document.getElementById('app'));

}).call(this);
