// Generated by CoffeeScript 1.10.0
(function() {
  var Main, RaisedButton, React, ReactDOM, a, div, h1, injectTapEventPlugin, p, ref;

  React = require('react');

  ReactDOM = require('react-dom');

  injectTapEventPlugin = require('react-tap-event-plugin');

  RaisedButton = require('material-ui/lib/raised-button');

  console.dir(React);

  console.dir(ReactDOM);

  console.dir(RaisedButton);

  ref = React.DOM, div = ref.div, h1 = ref.h1, p = ref.p, a = ref.a;

  console.dir(div);

  Main = React.createClass({
    render: function() {
      return div({
        className: "jumbotron"
      }, h1({}, "Hello World", p({}, a({
        className: "btn btn-primary btn-lg",
        href: "#",
        role: "button"
      }, "Learn more »"))), React.createElement(RaisedButton, {
        label: "Super Secret Password"
      }));
    }
  });

  injectTapEventPlugin();

  ReactDOM.render(React.createElement(Main), document.getElementById('app'));

}).call(this);
